using Bogus;
using SEBT.Portal.Core.Models.DocVerification;

namespace SEBT.Portal.TestUtilities.Helpers;

/// <summary>
/// Factory for creating DocVerificationChallenge instances using Bogus.
/// Used for testing. Follows the same pattern as UserFactory and HouseholdFactory.
/// </summary>
public static class DocVerificationChallengeFactory
{
    private static readonly Faker<DocVerificationChallenge> ChallengeFaker = new Faker<DocVerificationChallenge>()
        .RuleFor(c => c.Id, f => 0) // Auto-generated by database
        .RuleFor(c => c.PublicId, f => f.Random.Guid())
        .RuleFor(c => c.UserId, f => f.Random.Int(1, 10000))
        .RuleFor(c => c.SocureReferenceId, f => f.Random.Guid().ToString())
        .RuleFor(c => c.EvalId, f => f.Random.Guid().ToString())
        .RuleFor(c => c.SocureEventId, f => f.Random.Guid().ToString())
        .RuleFor(c => c.DocvTransactionToken, f => f.Random.Guid().ToString())
        .RuleFor(c => c.DocvUrl, (f, c) => $"https://verify.socure.com/#/dv/{c.DocvTransactionToken}")
        .RuleFor(c => c.DocvTokenIssuedAt, _ => DateTime.UtcNow)
        .RuleFor(c => c.AllowIdRetry, f => true)
        .RuleFor(c => c.CreatedAt, f => f.Date.Past(1))
        .RuleFor(c => c.UpdatedAt, (f, c) => f.Date.Between(c.CreatedAt, DateTime.UtcNow))
        .RuleFor(c => c.ExpiresAt, (f, c) => c.CreatedAt.AddMinutes(30));

    /// <summary>
    /// Creates a new challenge in the default Created state.
    /// </summary>
    /// <param name="customize">Optional action to customize the generated challenge.</param>
    /// <returns>A new DocVerificationChallenge instance in Created status.</returns>
    public static DocVerificationChallenge CreateChallenge(Action<DocVerificationChallenge>? customize = null)
    {
        var challenge = ChallengeFaker.Generate();
        customize?.Invoke(challenge);
        return challenge;
    }

    /// <summary>
    /// Creates a challenge for a specific user.
    /// UserId is init-only, so this uses a separate Faker clone with the userId baked in.
    /// </summary>
    /// <param name="userId">The user ID to assign the challenge to.</param>
    /// <param name="customize">Optional action to further customize the challenge.</param>
    /// <returns>A challenge assigned to the specified user.</returns>
    public static DocVerificationChallenge CreateChallengeForUser(
        int userId,
        Action<DocVerificationChallenge>? customize = null)
    {
        var faker = new Faker<DocVerificationChallenge>()
            .RuleFor(c => c.Id, _ => 0)
            .RuleFor(c => c.PublicId, f => f.Random.Guid())
            .RuleFor(c => c.UserId, _ => userId)
            .RuleFor(c => c.SocureReferenceId, f => f.Random.Guid().ToString())
            .RuleFor(c => c.EvalId, f => f.Random.Guid().ToString())
            .RuleFor(c => c.SocureEventId, f => f.Random.Guid().ToString())
            .RuleFor(c => c.DocvTransactionToken, f => f.Random.Guid().ToString())
            .RuleFor(c => c.DocvUrl, (f, c) => $"https://verify.socure.com/#/dv/{c.DocvTransactionToken}")
            .RuleFor(c => c.DocvTokenIssuedAt, _ => DateTime.UtcNow)
            .RuleFor(c => c.AllowIdRetry, _ => true)
            .RuleFor(c => c.CreatedAt, f => f.Date.Past(1))
            .RuleFor(c => c.UpdatedAt, (f, c) => f.Date.Between(c.CreatedAt, DateTime.UtcNow))
            .RuleFor(c => c.ExpiresAt, (f, c) => c.CreatedAt.AddMinutes(30));

        var challenge = faker.Generate();
        customize?.Invoke(challenge);
        return challenge;
    }

    /// <summary>
    /// Creates a challenge that has been transitioned to Pending status.
    /// </summary>
    /// <param name="customize">Optional action to further customize the challenge.</param>
    /// <returns>A challenge in Pending status with Socure correlation fields set.</returns>
    public static DocVerificationChallenge CreatePendingChallenge(Action<DocVerificationChallenge>? customize = null)
    {
        var challenge = ChallengeFaker.Generate();
        challenge.TransitionTo(DocVerificationStatus.Pending);
        customize?.Invoke(challenge);
        return challenge;
    }

    /// <summary>
    /// Creates a challenge that has been verified.
    /// </summary>
    /// <param name="customize">Optional action to further customize the challenge.</param>
    /// <returns>A challenge in Verified status.</returns>
    public static DocVerificationChallenge CreateVerifiedChallenge(Action<DocVerificationChallenge>? customize = null)
    {
        var challenge = ChallengeFaker.Generate();
        challenge.TransitionTo(DocVerificationStatus.Pending);
        challenge.TransitionTo(DocVerificationStatus.Verified);
        customize?.Invoke(challenge);
        return challenge;
    }

    /// <summary>
    /// Creates a challenge that has been rejected.
    /// </summary>
    /// <param name="offboardingReason">The rejection reason code.</param>
    /// <param name="customize">Optional action to further customize the challenge.</param>
    /// <returns>A challenge in Rejected status with offboarding reason.</returns>
    public static DocVerificationChallenge CreateRejectedChallenge(
        string offboardingReason = "docVerificationFailed",
        Action<DocVerificationChallenge>? customize = null)
    {
        var challenge = ChallengeFaker.Generate();
        challenge.OffboardingReason = offboardingReason;
        challenge.TransitionTo(DocVerificationStatus.Pending);
        challenge.TransitionTo(DocVerificationStatus.Rejected);
        customize?.Invoke(challenge);
        return challenge;
    }

    /// <summary>
    /// Sets a seed for the random number generator to ensure deterministic test data.
    /// </summary>
    /// <param name="seed">The seed value to use.</param>
    public static void SetSeed(int seed)
    {
        Randomizer.Seed = new Random(seed);
    }
}
